/* 「작품 정리」 문서에서 build_data.py 로 자동 생성. 직접 고치지 말고 문서를 고친 뒤 다시 생성할 것. */
var WORKS = [
 {
  "id": "bs-a",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "BLACK Silhouette(現影)",
  "ko": "현영現影",
  "y": "2025",
  "made": "2025",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Temporary Installation: 임시설치",
  "place": "Lahan Select Gyeongju, Gyeongju, Korea, 라한셀렉트 경주, 경주, 대한민국",
  "event": "Farewell Dinner for the High-Level Dialogue on Cultural Industries in Gyeongju: 경주 문화산업고위급대화 환송만찬",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-b",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "BLACK Silhouette(現影): 共生共思",
  "ko": "현영現影: 공생공사",
  "y": "2024",
  "made": "2024",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "The Lit, Hanam, Korea : 더릿, 하남, 대한민국",
  "event": "The Lit Symbiosis and Co-destruction Exhibition : 더릿 공생공사 전시전",
  "credit": "Sound source / Lee Ye-chan: 음향 / 이예찬",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-c",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然)",
  "ko": "형연泂然",
  "y": "2024",
  "made": "2024",
  "size": "Φ 227 x H 375cm, 3,088 Speakers, Mixed media",
  "type": "Permanent Installation: 영구설치",
  "place": "Gyeongsangbuk-do Provincial Office, Andong, Korea: 경상북도청, 안동, 대한민국",
  "event": "Gyeongsangbuk-do Provincial Office, Andong, Korea: 경상북도청, 안동, 대한민국",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art",
  "img": []
 },
 {
  "id": "bs-d",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Climate Resonance",
  "ko": "형연泂然: 기후공명",
  "y": "2024",
  "made": "2024",
  "size": "Φ 227 x H 375cm, 3,088 Speakers, Mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Gwanghwamun Square, Seoul, Korea: 광화문광장, 서울, 대한민국",
  "event": "2024 Climate Resonance Project, 2024 기후공명 프로젝트",
  "credit": "Sound source / Yoo Young-eun: 음향 / 유영은",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art",
  "img": []
 },
 {
  "id": "bs-e",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "BLACK Silhouette(現影)",
  "ko": "현영現影",
  "y": "2022",
  "made": "2022",
  "size": "Φ 227 x H 375cm, 3,088 Speakers, Mixed media",
  "type": "Private collection : 개인 소장",
  "place": "Kumho Albert Seoul, Seoul, Korea: 금호 알베르 서울, 서울, 대한민국",
  "event": "Exhibition 'The Silhouette': 전시전 '현영’",
  "credit": "Singer / Wonsuk Han: 가수 / 한원석",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-f",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Gyeongju",
  "ko": "형연泂然: 경주",
  "y": "2021",
  "made": "2021",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Private collection : 개인 소장",
  "place": "Gyeongju Expo Cultural Center, Gyeongju, Korea, 경주 엑스포 문화센터, 경주, 대한민국",
  "event": "Gyeongju Expo, 2021: 2021 경주 엑스포, 2021",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art",
  "img": []
 },
 {
  "id": "bs-g",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Reconcile",
  "ko": "형연泂然-화해의 울림",
  "y": "2011",
  "made": "2011",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Temporary Installation: 임시설치",
  "place": "Seoul Sejong Center for the Performing Arts, Seoul, Korea: 세종문화회관, 서울, 대한민국",
  "event": "The 48th Daejong Film Awards: 제 48회 대종상시상식",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-h",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Reconcile",
  "ko": "형연泂然-화해의 울림",
  "y": "2011",
  "made": "2011",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Incheon Art Platform, Incheon, Korea: 인천아트플랫폼, 인천, 대한민국",
  "event": "The 4th Anniversary of the Oct 4th South-North Joint Declaration: Sea of Conflict, Sea of Reconciliation, 2011: 10•4 남북공동선언 4주년 기념 <분쟁의 바다 화해의 바다>, 2011",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "bs-i",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Audi A8 Pavilion",
  "ko": "형연泂然: 아우디 A8 파빌리온",
  "y": "2010",
  "made": "2010",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Olympic Park, Seoul, Korea: 올림픽공원, 서울, 대한민국",
  "event": "Audi A8 Pavilion, 2010: 아우디 A8 파빌리온, 2010",
  "credit": "Composer  / AUDI HEARTBEAT: 작곡 / AUDI HEARTBEAT",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-j",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然)",
  "ko": "형연泂然",
  "y": "2010",
  "made": "2010",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Cheonggyecheon, Seoul, Korea, 2010: 청계천, 서울, 대한민국, 2010",
  "event": "Peace Prayer Festival for the 60th Anniversary of the Korean War, 2010: 6·25 60주년 평화염원 범국민 한마당, 2010",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art",
  "img": []
 },
 {
  "id": "bs-k",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Korean Embassy",
  "ko": "형연泂然: 주한대사관",
  "y": "2008",
  "made": "2008",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "The Korea Ambassador’s residence, Beijing, China, 2008: 주중 한국대사관 저, 베이징, 중국, 2008",
  "event": "The Korea Ambassador’s residence, Beijing, China, 2008: 주중 한국대사관 저, 베이징, 중국, 2008",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-l",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然): Busan Biennale",
  "ko": "형연泂然: 부산 비앤날레",
  "y": "2008",
  "made": "2008",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Busan Biennale, Busan, Korea: 부산 비엔날레, 부산, 대한민국",
  "event": "2008 Busan Biennale: 2008 부산 비엔날레",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-m",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Resonance(泂然)",
  "ko": "형연泂然",
  "y": "2008",
  "made": "2008",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Solo exhibition: 개인전",
  "place": "798 Art District, Dashanzi, Beijing, China: 798 예술구 다산쯔, 베이징, 중국",
  "event": "798 Dashanzi Exhibition for 2008 Beijing Olympics: 2008 베이징 올림픽 기념 798 다산쯔 예술 축제",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "bs-n",
  "cat": "Installation",
  "series": "BLACK SILHOUETTE",
  "t": "Narae-soebuk",
  "ko": "나래쇠북",
  "y": "2008",
  "made": "2008",
  "size": "Φ 227 x H 375cm, 3,088 Speakers",
  "type": "Permanent Installation: 영구설치",
  "place": "New National Science Museum, Gwacheon, Korea: 과천국립과학관, 대한민국",
  "event": "The South Korea National Science center Opening: 新 국립과학관 건립 기념식",
  "credit": "Sound source / Kim Tae-geun: 음향 / 김태근",
  "tags": "Sound / Light / Interactive / Site-specific / Public Art",
  "img": []
 },
 {
  "id": "st-a",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "PAPAGENO",
  "ko": "파파게노",
  "y": "2023",
  "made": "2023",
  "size": "Φ122mm Paper tube 10T, Speakers, Mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Suan Art House, Busan, Korea: 수안아트하우스, 부산, 대한민국",
  "event": "Exhibition 'Re:Vertical (Stand Again)' at Suan Art House: 수안아트하우스 전시전 ‘Re:Vertical (다시, 서다)’",
  "credit": "Sound source / Won-mi Kim: 음향 / 김원미",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-b",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Thought within the Black Hole",
  "ko": "검은 구멍의 혀",
  "y": "2025",
  "made": "2025",
  "size": "400cm X 600cm X (H) 400cm, paper tube, mixed media",
  "type": "Solo exhibition: 개인전",
  "place": "Dongil Rubber Belt Dongrae Factory, Busan, Korea: 동일고무벨트 동래공장, 부산, 한국",
  "event": "Exhibition The Thought within the Black Hole Exhibition: 전시전 ‘지각의 경계: 검은 구멍 속 사유’",
  "credit": "Curator /  Eun-young Gim Choe: 기획 / 김최은영\nSound source / Young-eun Yoo: 음향 / 유영은\nPerformance / Ye-chan Lee, Gwan-ji Kim, Hye-in Pyo: 퍼포먼스 / 이예찬, 김관지, 표혜인",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-c",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Re-Forest Sound Pavilion: DDP",
  "ko": "리-포레스트 사운드 파빌리온: DDP",
  "y": "2024",
  "made": "2024",
  "size": "400cm X 600cm X (H) 400cm, paper tube, mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Dongdaemun Design Plaza, Seoul, Korea: 동대문디자인플라자, 서울, 대한민국",
  "event": "Seoul Design Festival 2024: 서울디자인페스티벌 2024",
  "credit": "Sound source / Young-eun Yoo: 음향 / 유영은",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "st-d",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Re-Forest Sound Pavilion",
  "ko": "리-포레스트 사운드 파빌리온",
  "y": "2024",
  "made": "2024",
  "size": "400cm X 600cm X (H) 400cm, paper tube, mixed media",
  "type": "Solo exhibition: 개인전",
  "place": "Paik Hae Young Gallery, Seoul, Korea: 백해영 갤러리, 서울, 대한민국",
  "event": "Won-seok Han Solo Exhibition 'RE:forest Sound Pavilion' at Paik Hae Young Gallery: 백해영갤러리 한원석 개인전 ‘RE:forest Sound Pavilion'",
  "credit": "Sound source / Young-eun Yoo: 음향 / 유영은",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-e",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Tree",
  "ko": "소리나무",
  "y": "2024",
  "made": "2024",
  "size": "Φ12 x H 190cm",
  "type": "Private collection : 개인 소장",
  "place": "A Jujube Field Oriental Medical Clinic, Gyeongju, Korea: 대추밭한의원, 경주, 대한민국",
  "event": "A Jujube Field Oriental Medical Clinic: 대추밭한의원",
  "credit": "Composer / Young-eun Yoo: 작곡가 / 유영은",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-f",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Tree",
  "ko": "소리나무",
  "y": "2024",
  "made": "2024",
  "size": "Φ12 x H 190cm",
  "type": "Team Exhibition: 기획전",
  "place": "Itami Jun Museum, Jeju, Korea: 유동룡미술관, 제주, 대한민국",
  "event": "Exhibition 'Artists with Warm Hands: Carrying Forward the Warmth' at Itami Jun Museum: 유동룡미술관 전시전 ‘손이 따뜻한 예술가들: 그 온기를 이어가다’",
  "credit": "Composer / Young-eun Yoo: 작곡가 / 유영은",
  "tags": "Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-g",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Norwegian Wood(This Bird has Flown)",
  "ko": "노르웨이의 숲",
  "y": "2024",
  "made": "2024",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Permanent Installation: 영구설치",
  "place": "FEZH, Seoul, Korea: 페즈, 한남동, 서울, 대한민국",
  "event": "FEZH: 페즈",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim  : 음향 / 김태근,김창훈",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-h",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "PAPAGENO RE: DREAM",
  "ko": "파파게노 RE: DREAM",
  "y": "2023",
  "made": "2023",
  "size": "Φ122mm Paper tube 10T, Speakers, Mixed media",
  "type": "Solo exhibition: 개인전",
  "place": "Hyundai Department Store Mokdong Branch, Seoul, Korea: 현대백화점 목동점, 서울, 대한민국",
  "event": "Exhibition 'Papageno' at Hyundai Department Store Mokdong Branch: 현대백화점 목동점 전시전 ‘파파게노’",
  "credit": "Composer / Siyul   : 작곡가 / 시율",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-i",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest",
  "ko": "소리숲",
  "y": "2022",
  "made": "2022",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Solo exhibition: 개인전",
  "place": "Artside Gallery, Seoul, Korea: 아트사이드갤러리, 서울, 대한민국",
  "event": "Exhibition 'The Resonance Forest' at Artside Gallery: 아트사이드갤러리 전시전 ‘공명의 숲’",
  "credit": "Composer / Yong-jun Yang: 작곡가 / 양용준",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-j",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Gwan-Eum(觀音) III",
  "ko": "관음(觀音) III",
  "y": "2015",
  "made": "2015",
  "size": "Φ12 x H 300cm Paper Cylinder 15ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "six ELZEVIR Gallery, Paris, France: 삭스 엘제비르 갤러리, 파리, 프랑스",
  "event": "Exhibition 'CHAMBRES BONDÉES': 전시전 ‘CHAMBRES BONDÉES’",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-k",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Gwan-Eum(觀音) II - Spirit of Spirit",
  "ko": "관음(觀音) II - 혼의 혼",
  "y": "2015",
  "made": "2015",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Glenfiddich Distillery, Dufftown, Scotland: 글렌피딕 증류소, 더프타운, 스코틀랜드",
  "event": "2014 Glenfiddich Artist in Residence Program at Glenfiddich Distillery: 글렌피딕 증류소 ‘2014 글렌피딕 아티스트 챌린지 to 스코틀랜드’ (글렌피딕 문화예술 레지던스 프로그램)",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-l",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest: Earth 展",
  "ko": "소리숲: 지구 展",
  "y": "2011",
  "made": "2011",
  "size": "Φ12 x H 300cm Paper Cylinder 12ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Seongbuk District Art Museum, Seoul, Korea: 성북구립미술관, 서울, 대한민국",
  "event": "Exhibition 'The Earth 展': 전시전 ‘지구 · The Earth 展’",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim  : 음향 / 김태근,김창훈",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "st-m",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest",
  "ko": "소리숲",
  "y": "2011",
  "made": "2011",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Private collection : 개인 소장",
  "place": "Artside Gallery, Seoul, Korea: 아트사이드갤러리, 서울, 대한민국",
  "event": "Artside Gallery: 아트사이드갤러리",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim  : 음향 / 김태근,김창훈",
  "tags": "Sound / Light / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "st-n",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest",
  "ko": "소리숲",
  "y": "2011",
  "made": "2011",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Private collection : 개인 소장",
  "place": "Colamercato Sinsa, Seoul, Korea: 꼴라메르까토 신사점, 서울, 대한민국",
  "event": "Colamercato Sinsa: 꼴라메르까토 신사점",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim  : 음향 / 김태근,김창훈",
  "tags": "Sound / Light / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "st-o",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Gwan-Eum(觀音) I",
  "ko": "관음(觀音) I",
  "y": "2010",
  "made": "2010",
  "size": "Φ12 x H 300cm Paper Cylinder 15ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "AT Center, Seoul, Korea: AT센터, 서울, 대한민국",
  "event": "Exhibition '2010 Ceramic Art & Technology': 전시전 ‘2010 세라믹 아트 & 테크놀로지’",
  "credit": "Composer / Tae-geun Kim: 작곡가 / 김태근",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-p",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest III",
  "ko": "소리숲 III",
  "y": "2010",
  "made": "2010",
  "size": "Φ12 x H 300cm Paper Cylinder, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Olympic Park, Seoul, Korea: 올림픽공원, 서울, 대한민국",
  "event": "Audi A8 Pavilion, 2010: 아우디 A8 파빌리온, 2010",
  "credit": "Composer  / AUDI HEARTBEAT: 작곡 / AUDI HEARTBEAT",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-q",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest II",
  "ko": "소리숲 II",
  "y": "2010",
  "made": "2010",
  "size": "Φ12 x H 300cm Paper Cylinder 82ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Seoul Trade Exhibition & Convention Center (SETEC), Seoul, Korea: 서울무역전시컨벤션센터 (SETEC), 서울, 대한민국",
  "event": "Exhibition 'Four Rooms': 전시전 ‘Four Rooms’",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim: 음향 / 김태근,김창훈",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-r",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest II - Sublime",
  "ko": "소리숲 II - 숭고",
  "y": "2009",
  "made": "2009",
  "size": "Φ12 x H 300cm Paper Cylinder 82ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "Icheon Art Hall, Icheon, Korea: 이천아트홀, 이천, 대한민국",
  "event": "Exhibition '7 Things I Want to Know About Arts’, Icheon Art Hall Opening Exhibition: 전시전 ‘미술에 대해 알고 싶은 일곱 가지 것들’, 이천아트홀 개관기념전",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim: 음향 / 김태근,김창훈",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "st-s",
  "cat": "Installation",
  "series": "SOUND TREE",
  "t": "Sound Forest I",
  "ko": "소리숲 I",
  "y": "2009",
  "made": "2009",
  "size": "Φ12 x H 300cm Paper Cylinder 82ea, Speakers",
  "type": "Team Exhibition: 기획전",
  "place": "JANET OH Gallery, Seoul, Korea: 자넷오 갤러리, 서울, 대한민국",
  "event": "Exhibition 'Sound Forest': 전시전 ‘Sound Forest’",
  "credit": "Sound source / Tae-geun Kim,Chang-hoon Kim: 음향 / 김태근,김창훈",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "rb-a",
  "cat": "Installation",
  "series": "REBIRTH",
  "t": "Rebirth(還生): Silla Cultural Festival",
  "ko": "환생(還生): 신라문화제",
  "y": "2021",
  "made": "2021",
  "size": "Φ514 x 915cm, 1,374 discarded-headlights, LED",
  "type": "Team Exhibition: 기획전",
  "place": "Bong Hwang Dae Plaza, Gyeongju, Korea: 봉황대 광장, 경주, 대한민국",
  "event": "The 48th Silla Cultural Festival: 제48회 신라문화제",
  "credit": "없음",
  "tags": "Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "rb-b",
  "cat": "Installation",
  "series": "REBIRTH",
  "t": "Rebirth(還生)",
  "ko": "환생(還生)",
  "y": "2021",
  "made": "2021",
  "size": "Φ514 x 915cm, 1,374 discarded-headlights, LED",
  "type": "Permanent Installation: 영구설치",
  "place": "Gyeongsangbuk-do Provincial Office, Andong, Korea: 경상북도청, 안동, 대한민국",
  "event": "Gyeongsangbuk-do Provincial Office: 경상북도청",
  "credit": "없음",
  "tags": "Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "rb-c",
  "cat": "Installation",
  "series": "REBIRTH",
  "t": "Rebirth(還生): Shine a light of hope",
  "ko": "환생(還生): 천년의 빛으로 희망을 비추다",
  "y": "2020",
  "made": "2020",
  "size": "Φ514 x 915cm, 1,374 discarded-headlights, LED",
  "type": "Solo exhibition: 개인전",
  "place": "Seoul Urbanism and Architecture Exhibition Hall, Seoul, Korea: 서울도시건축문화전시관, 서울, 대한민국",
  "event": "Exhibition 'Re:relationship': 전시전 ‘Re:relationship’",
  "credit": "없음",
  "tags": "Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "rb-d",
  "cat": "Installation",
  "series": "REBIRTH",
  "t": "Rebirth(還生)",
  "ko": "환생(還生)",
  "y": "2014",
  "made": "2014",
  "size": "Φ514 x 915cm, 1,374 discarded-headlights, LED",
  "type": "Team Exhibition: 기획전",
  "place": "Suncheon Bay National Garden, Suncheon, Korea: 순천만국가정원, 순천, 대한민국",
  "event": "Suncheon Bay National Garden:순천만국가정원",
  "credit": "없음",
  "tags": "Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "rb-e",
  "cat": "Installation",
  "series": "REBIRTH",
  "t": "Rebirth(還生)",
  "ko": "환생(還生)",
  "y": "2006",
  "made": "2006",
  "size": "Φ514 x 915cm, 1,374 discarded-headlights, LED",
  "type": "Solo exhibition: 개인전",
  "place": "Cheonggyecheon, Seoul, Korea: 청계천, 서울, 대한민국",
  "event": "Won-seok Han Solo Exhibition, 2006 Cheonggyecheon Festival: 한원석 초대전, 2006 청계천 축제",
  "credit": "없음",
  "tags": "Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "rc-a",
  "cat": "Installation",
  "series": "RECONCILED",
  "t": "Daybreak: A dreamy journey",
  "ko": "여명: 몽환의 여행",
  "y": "2022",
  "made": "2022",
  "size": "(w)6.56 x (h)1.96m, Steel Structure, Waste Speakers",
  "type": "Solo exhibition: 개인전",
  "place": "Hyundai Department Store Mokdong Branch, Seoul, South Korea: 현대백화점 목동점, 서울, 대한민국",
  "event": "Exhibition 'Dreamlike Soundscape': 전시전 '몽환의 여행’",
  "credit": "Sound source / Min-ji Kim: 음향 / 김민지",
  "tags": "Sound / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "rc-b",
  "cat": "Installation",
  "series": "RECONCILED",
  "t": "The Resonance Forest",
  "ko": "공명의 숲",
  "y": "2022",
  "made": "2022",
  "size": "The Re-origin - Resin, Mixed media | Daybreak - Speaker, Mixed media",
  "type": "Solo exhibition: 개인전",
  "place": "Artside Gallery, Seoul, Korea: 아트사이드갤러리, 서울, 대한민국",
  "event": "Exhibition 'The Resonance Forest' at Artside Gallery: 아트사이드갤러리 전시전 ‘공명의 숲’",
  "credit": "Composer / Yong-jun Yang: 작곡가 / 양용준",
  "tags": "Installation / Sound / Light / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "rc-c",
  "cat": "Installation",
  "series": "RECONCILED",
  "t": "Daybreak 82 x 23",
  "ko": "여명 82 x 23",
  "y": "2021",
  "made": "2021",
  "size": "(w)6.56 x (h)1.96m, Steel Structure, Waste Speaker",
  "type": "Solo exhibition: 개인전",
  "place": "Kumho Albert Seoul, Seoul, Korea: 금호 알베르 서울, 서울, 대한민국",
  "event": "Exhibition 'Daybreak': 전시전 'Daybreak'",
  "credit": "Composer / Yong-jun Yang: 작곡가 / 양용준",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "rc-d",
  "cat": "Installation",
  "series": "RECONCILED",
  "t": "Reconciled Ⅱ",
  "ko": "화해Ⅱ",
  "y": "2011",
  "made": "2011",
  "size": "(w)2.45 x (d)6.9 x (h) 2.75 m, Steel Structure, Waste Speakers",
  "type": "Solo exhibition: 개인전",
  "place": "Incheon Art Platform, Incheon, Korea: 인천아트플랫폼, 인천, 대한민국",
  "event": "Exhibition 'Sea of Peace': 전시전 '평화의 바다’",
  "credit": "Singer / Jeong-jae Cha: 가수 / 차정재",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "rc-e",
  "cat": "Installation",
  "series": "RECONCILED",
  "t": "Reconciled I",
  "ko": "화해 I",
  "y": "2011",
  "made": "2011",
  "size": "1,000 x 500 x H300cm 16,360 Speakers, Ottchill on the Paper Cylinder, Sound System",
  "type": "Solo exhibition: 개인전",
  "place": "Gallery Absinthe, Seoul, Korea: 갤러리 압생트, 서울, 대한민국",
  "event": "Exhibition 'Reconciled': 전시전 '화해’",
  "credit": "Composer / Tae-geun Kim : 작곡가 / 김태근",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "fe-a",
  "cat": "Installation",
  "series": "THE FLOWER OF EVIL",
  "t": "The Flower of Evil",
  "y": "2003",
  "made": "2003",
  "size": "Burned Out: 99 x 122 cm, 7,870 cigarette butts\nTrace: 122 x 92 cm,  cigarette butts\nGreedy Flower: 92 x 122 cm, 17,196 cigarette butts\nBurning: 192 x 215 cm, 73,000 cigarette butts\nSelf Portrait(L): 103 x 128 cm, 21,203 cigarette butts\nSelf Portrait(R): 63 x 128cm, 13,304 cigarette butts\nStupid Smile: 168 x 62 cm, 574 cigarette butts\nOh! korea: 92 x 122 cm, 17,287 Cigarette butts\nSnow: 92 x 122 cm, 17,280 Cigarette butts\nStar (12 pieces): 54 x 54 cm, 1,147 cigarette butts",
  "type": "Solo exhibition: 개인전",
  "place": "Artside Gallery, Seoul, Korea: 아트사이드 갤러리, 서울, 대한민국",
  "event": "1st Solo Exhibition 'The Flower of Evil': 첫번째 개인전 '악의 꽃’",
  "credit": "없음",
  "tags": "Installation",
  "note": "Burned Out, Trace, Greedy Flower, Burning, Self Portrait(L), Self Portrait(R), Stupid Smile, Oh! korea, Snow, Star (12 pieces)",
  "img": []
 },
 {
  "id": "ow-a",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Re:moon(還月)",
  "ko": "환월(還月)",
  "y": "2026",
  "made": "2026",
  "size": "Φ365 x 365cm, discarded-headlights, Discarded rubbers, LED, mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Busan Museum, Busan, Korea: 부산박물관, 부산, 대한민국",
  "event": "Exhibition 'Journey of the Moon: Busan Moon Jar': 전시전 '달의 여정: 부산 달항아리’",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-b",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Re:moon(還月)",
  "ko": "환월(還月)",
  "y": "2025",
  "made": "2025",
  "size": "Φ365 x 365cm, discarded-headlights, discarded rubbers, LED, mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Haeundae Dalmaji Park, Busan, Korea: 해운대 달맞이공원, 부산, 대한민국",
  "event": "Exhibition 'Eternal Moonlight Park’': 전시전 '달, 머무는 공원’",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-c",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Re:moon(還月)",
  "ko": "환월(還月)",
  "y": "2025",
  "made": "2025",
  "size": "Φ365 x 365cm, discarded-headlights, discarded rubbers, LED, mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Cheonggyecheon Stream, Seoul, Korea: 청계천, 서울, 대한민국",
  "event": "2025 Seoul Lantern Festival in Cheonggyecheon: 2025 청계천 빛초롱 축제",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-d",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Void Circle(環影)",
  "ko": "환영(環影)",
  "y": "2025",
  "made": "2025",
  "size": "Φ2,870 x 4,550 mm, stainless steel pipes, speakers, mixed media",
  "type": "Temporary Installation: 임시설치",
  "place": "Gyeongbuk Culture & Tourism Organization (GCTO) Headquarters, Gyeongju, Korea: 경상북도문화관광공사 청사, 경주, 대한민국",
  "event": "Gyeongbuk Culture & Tourism Organization (GCTO) Headquarters: 경상북도문화관광공사 청사",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-e",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Void Circle(環影)",
  "ko": "환영(環影)",
  "y": "2025",
  "made": "2025",
  "size": "Φ2,870 x 4,550 mm, stainless steel pipes, speakers, mixed media",
  "type": "Temporary Installation: 임시설치",
  "place": "Dong-gu Culture Platform, Busan, Korea: 동구문화플랫폼, 부산, 대한민국",
  "event": "Dong-gu Culture Platform: 동구문화플랫폼",
  "credit": "없음",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-f",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Re-one(不.二.火): 共生共思",
  "ko": "불이화(不.二.火): 공생공사",
  "y": "2024",
  "made": "2024",
  "size": "(w)400 x (d)350 x (h)400cm, Paper tube 10T (ø)122mm, Speaker, LED, Mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "The Lit, Hanam, Korea : 더릿, 하남, 대한민국",
  "event": "The Lit Symbiosis and Co-destruction Exhibition : 더릿 공생공사 전시전",
  "credit": "Composer / Siyul: 작곡가 / 시율",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "ow-g",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Re-one(不.二.火)",
  "ko": "불이화(不.二.火)",
  "y": "2023",
  "made": "2023",
  "size": "(w)400 x (d)350 x (h)400cm, Paper tube 10T (ø)122mm, Speaker, LED, Mixed media",
  "type": "Team Exhibition: 기획전",
  "place": "Kumho Albert Seoul, Seoul, Korea: 금호 알베르 서울, 서울, 대한민국",
  "event": "Exhibition 'Re-one(不.二.火)': 전시전 ‘불.이.화(不.二.火)’",
  "credit": "Composer / Siyul: 작곡가 / 시율",
  "tags": "Installation / Sound / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "ow-h",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Towards(向): Indigo Sky",
  "ko": "향(向) : 쪽빛 하늘",
  "y": "2020",
  "made": "2020",
  "size": "(w)20.21 x (d)19.65 x (h)8.15m, 64˚, Stainless Steel Plate 101 pieces, 5,775 Fiber Optic strands, LED",
  "type": "Permanent Installation: 영구설치",
  "place": "Gyeongsangbuk-do Provincial Office, Andong, Korea: 경상북도청, 안동, 대한민국",
  "event": "Gyeongsangbuk-do Provincial Office: 경상북도청",
  "credit": "없음",
  "tags": "Installation / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-i",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Glittering Pathway(到耿)",
  "ko": "도경(到耿)",
  "y": "2019",
  "made": "2019",
  "size": "(d)77.2 x (h)22.7m",
  "type": "Solo exhibition: 개인전",
  "place": "BNK Busan Bank Sinchang-dong Branch, Busan, Korea: BNK 부산은행 신창동지점, 부산, 대한민국",
  "event": "BNK Busan Bank Sinchang-dong Branch: BNK 부산은행 신창동지점",
  "credit": "없음",
  "tags": "Installation / Light / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-j",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Moon Window(月窓)",
  "ko": "달의 창(月窓)",
  "y": "2014",
  "made": "2014",
  "size": "(w)8 x (d)4 x (h)9.1m",
  "type": "Team Exhibition: 기획전",
  "place": "Masan Central Pier, Changwon, Korea: 마산중앙부두, 창원, 대한민국",
  "event": "2014 Changwon Sculpture Biennale: 2014 창원조각비엔날레",
  "credit": "없음",
  "tags": "Installation / Interactive / Site-specific / Public Art / Pavilion",
  "img": []
 },
 {
  "id": "ow-k",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Mother's arms",
  "ko": "엄마의 품",
  "y": "2010",
  "made": "2010",
  "size": "Φ2.4 X 2.7m, 365 Discarded-headlights, LED",
  "type": "Permanent Installation: 영구설치",
  "place": "LIG Nex1 Employee Apartment, Gumi, Korea: LIG넥스원 사원아파트, 구미, 대한민국",
  "event": "LIG Nex1: LIG넥스원",
  "credit": "없음",
  "tags": "Installation / Light / Interactive / Site-specific / Pavilion",
  "img": []
 },
 {
  "id": "ow-l",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "The Fool Game",
  "ko": "바보 게임",
  "y": "2002",
  "made": "2002",
  "size": "Unknown",
  "type": "Team Exhibition: 기획전",
  "place": "Borrowed Space Time Bound, Adaptable Function, London, UK: Borrowed Space Time Bound, Adaptable Function, 런던, 영국",
  "event": "Project 'The Fool Game': 프로젝트 ‘바보 게임’",
  "credit": "없음",
  "tags": "Installation / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "ow-m",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Multifunction of the Value: Through the Public Toilet",
  "ko": "공중 변기를 통한 가치의 다기능",
  "y": "2002",
  "made": "2002",
  "size": "Unknown",
  "type": "Team Exhibition: 기획전",
  "place": "Chelsea College of Arts, London, UK: 첼시 예술대학, 런던, 영국",
  "event": "Project 'Multifunction of the Value': 프로젝트 ‘가치의 다기능성’",
  "credit": "없음",
  "tags": "Installation / Interactive / Site-specific",
  "img": []
 },
 {
  "id": "ow-n",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Étude",
  "ko": "습작",
  "y": "1989",
  "made": "1989 - 1999",
  "size": "Sculpture A: 87 x 193cm, 1998\nSculpture B: 75 x 190cm, 1997\nSculpture C: 148 x 184cm, 1995\nSculpture D: 36 x 380cm, 65 x 395cm, 1994\nSculpture E: 230 x 102cm, 1993\nPainting A: 116.7 x 91.2cm, 1998\nPainting B: 60.5 x 72.5cm, 1995\nPainting C: 72.5 x 60.5cm, 1995\nPainting D: 72.5 x 60.5cm, 1994\nPainting E: 90.5 x 72.5cm, 1993\nPainting F: 117 x 91cm, 1992\nPainting G: 116.7 x 91.2cm, 1992\nPainting H: 116.5 x 90cm, 1992\nPainting I: 116.7 x 91.2cm, 1991\nPainting J: 90.5 x 117.5cm, 1991\nPainting K: 116.4 x 90.2cm, 1990\nPainting L: 103 x 73cm, 1990\nPainting M: 70.3 x 90.5cm, 1989\nPainting N: 70.3 x 90.5cm, 1989\nPainting O: 72.6 x 90.7cm, 1988",
  "type": "Team Exhibition: 기획전",
  "place": "Unknown",
  "event": "Unknown",
  "credit": "없음",
  "tags": "Installation",
  "note": "Sculpture - Untitled 5 Sculptures; Painting - Untitled 17 Paintings",
  "yfull": "1989 - 1999",
  "img": []
 },
 {
  "id": "ow-o",
  "cat": "Installation",
  "series": "OTHER WORKS",
  "t": "Won-seok Han's Drawing Book",
  "ko": "한원석 드로잉북",
  "y": "1989",
  "made": "1989",
  "size": "35.2 x 25 cm, 10pages sketch, essay, diary, letter",
  "type": "Unknown",
  "place": "Unknown",
  "event": "Unknown",
  "credit": "없음",
  "tags": "없음",
  "img": []
 },
 {
  "id": "ar-a",
  "cat": "Architectural",
  "t": "2025 APEC Banquet Hall",
  "ko": "2025 APEC 만찬장",
  "y": "2025",
  "made": "Not determined",
  "size": "대지면적: 66,408m²\n건축면적: 9,008.27m²(기존건물) + 2,068.35m²(만찬장)\n연면적: 18,883.87m²(기존건물) + 2,068.35m²(만찬장)\n건폐율: 16.68% / 자연녹지지역 20%\n용적률: 24.58% / 자연녹지지역 100%\n층수: 1F",
  "type": "Design",
  "place": "Courtyard, Gyeongju National Museum, Gyeongju, Korea: 국립경주박물관 내 중정 일원, 경주, 대한민국",
  "event": "2025 APEC: 2025 APEC",
  "credit": "건축가: 차운기",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-b",
  "cat": "Architectural",
  "t": "Bloom Up",
  "ko": "블룸 업",
  "y": "2019",
  "made": "Not determined",
  "size": "대지면적: 977.8m²\n건축면적: 488.82m²\n연면적: 3,066.47m²\n건폐율: 49.99%\n용적률: 178.57%\n층수: B3-5F",
  "type": "Design",
  "place": "Jung-gu, Seoul, Korea: 중구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n계획설계(SD): 신지섭\n설계개발(DD): 신지섭 + KDA",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-c",
  "cat": "Architectural",
  "t": "VillageBus 6",
  "ko": "금사동 6번 마을버스",
  "y": "2019",
  "made": "완공시기: 2019년 5월",
  "size": "대지면적: 339.8m²\n건축면적: 134.19m²\n연면적: 209.82m²\n건폐율: 39.49%\n용적률: 61.75%\n층수: 2F",
  "type": "Design and Construction",
  "place": "Geumjeong-gu, Busan, Korea: 금정구, 부산, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n계획설계(SD): 신지섭\n설계개발(DD): 신지섭 + Easyarch corp.\n시공: 삼원테크",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-d",
  "cat": "Architectural",
  "t": "2018 PyeongChang Winter Olympic Festival Park",
  "ko": "2018 평창동계올림픽 페스티벌파크 평창&강릉관",
  "y": "2018",
  "made": "완공시기: 2018년 1월",
  "size": "평창관\n대지면적: 15,728m² / 4,757.72py\n건축면적: 9,316m² / 2,818.09py\n연면적: 9,316m² / 2,818.09py\n높이: 15.83m\n층수: 2F\n강릉관\n대지면적: 5,079m² / 1,536.40py\n건축면적: 4,872m² / 1,473.78py\n연면적: 4,872m² / 1,473.78py\n높이: 13.3m\n층수: 3F",
  "type": "Design and Construction",
  "place": "평창관\n310-2 Hoenggye-ri, Daegwalnyeong-myeon, Pyeongchang-gun, Gangwon-do, Korea: 횡계리 310-2, 대관령면, 평창군, 강원특별자치도, 대한민국\n강릉관\n176 Yongji-ro, Gangneung-si, Gangwon-do, Korea: 용지로 176, 강릉시, 강원특별자치도, 대한민국",
  "event": "PyeongChang Winter Olympic: 평창동계올림픽",
  "credit": "건축가: 한원석\n계획설계(SD): 신지섭\n설계개발(DD): 신지섭\n프로젝트대행사: EZPMP\n시공: Mano E\\&I\n구조: Container + Alu Hall Tent, TFS Tent\n토목: 동림 C\\&E\n철골: KOK Architects\n텐트: 대원 Corp.\n컨테이너: 휴먼 C\\&D\nLED 유리: Wall Korea Networks Corp.\n외장공사: Danpal Korea",
  "tags": "용도: 갤러리 , 극장, 홍보관, 스토어",
  "img": []
 },
 {
  "id": "ar-e",
  "cat": "Architectural",
  "t": "SAMSUNG BLUE SQUARE Renewal",
  "ko": "삼성 블루스퀘어 리뉴얼",
  "y": "2016",
  "made": "완공시기: 2017년 1월",
  "size": "대지면적: 10,826m² / 3,274.87py\n건축면적: 5,910.32m² / 1,787.87py\n증축면적: 622.9m² / 188.43py\n연면적: 30,250.17m² / 9,150.68py\n건폐율: 54.59%\n용적률: 72.73%\n높이: 17m\n층수: B4-4F",
  "type": "Planning and Design",
  "place": "Yongsan-gu, Seoul, Korea: 용산구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n설계개발(DD): H-Lab + 나범식\n시공: PM Construction\n인테리어 디자인: H-Lab + Architect 2B",
  "tags": "용도: 북카페, 갤러리, F\\&B",
  "img": []
 },
 {
  "id": "ar-f",
  "cat": "Architectural",
  "t": "2014 Sochi Winter Olympics PyeongChang House Conception 胎夢",
  "ko": "2014 소치 동계올림픽 평창하우스 태몽(胎夢)",
  "y": "2014",
  "made": "완공시기: 2013년 11월",
  "size": "건축면적: 429.22㎡ / 129.84py\n연면적: 884.94㎡ / 267.71py\n높이: 15m\n층수: 3F",
  "type": "Planning and Design",
  "place": "Adler, Krasnodar Krai, Russia: 아들레르, 크라스노다르 지방, 러시아",
  "event": "2014 Sochi Winter Olympics: 2014 소치동계올림픽",
  "credit": "건축가: 한원석\n계획설계(SD): 신지섭",
  "tags": "용도: 갤러리, 극장, 홍보관, 스토어",
  "img": []
 },
 {
  "id": "ar-g",
  "cat": "Architectural",
  "t": "Benz Pavilion",
  "ko": "벤츠 파빌리온",
  "y": "2013",
  "made": "Not determined",
  "size": "Not determined",
  "type": "Planning and Design",
  "place": "Not determined",
  "event": "Benz: 벤츠",
  "credit": "Not determined",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-h",
  "cat": "Architectural",
  "t": "NEMO",
  "ko": "네모",
  "y": "2012",
  "made": "완공시기: 2012년 5월",
  "size": "대지면적: 652.65㎡ / 197.43py\n건축면적: 173.46㎡ / 52.47py\n연면적: 454.38㎡ / 137.45py\n건폐율: 26.73%\n용적률: 69.62%\n높이: 9m\n층수: 3F",
  "type": "Design and Construction",
  "place": "Yongsan-gu, Seoul, Korea: 용산구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n설계개발(DD): H-Lab\n시공: Ryu Construction.Co.\n구조 엔지니어: STECH Consulting Group\n컨테이너 제조업체: Human C\\&D\n외장 시공업체: Danpal Korea",
  "tags": "용도: 문화 및 집회시설 / 갤러리",
  "img": []
 },
 {
  "id": "ar-i",
  "cat": "Architectural",
  "t": "Dangjin K’s House",
  "ko": "당진 K씨 주택",
  "y": "2010",
  "made": "완공시기: 2013년 9월",
  "size": "대지면적: 1,833m²\n건축면적: 218.75m²\n연면적: 626.80m²\n건폐율: 11.93%\n용적률: 19.52%\n층수: B1 - 2F",
  "type": "Design and Construction",
  "place": "Dangjin-si, Chungcheongnam-do, Korea: 당진시, 충청남도, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n컨셉디자인: 한원석 + H-Lab\n기본설계(SD): 한원석 + H-Lab\n설계개발(DD): H-Lab + 예감 Architects\n시공: 김웅진\n인테리어 디자인: H-Lab",
  "tags": "용도: 주거",
  "img": []
 },
 {
  "id": "ar-j",
  "cat": "Architectural",
  "t": "RIZOME Renewal",
  "ko": "RIZOME 리뉴얼",
  "y": "2009",
  "made": "완공시기: 2010년 5월",
  "size": "연면적: 301.06m² / 91.07py",
  "type": "Design and Construction",
  "place": "Seocho-gu, Seoul, Korea: 서초구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n컨셉디자인: 한원석 + H-Lab\n기본설계(SD): 한원석 + H-Lab",
  "tags": "용도: 주거",
  "img": []
 },
 {
  "id": "ar-k",
  "cat": "Architectural",
  "t": "Calla(Ever-one Medical Mall)",
  "ko": "카라(에버원 메디컬 몰)",
  "y": "2009",
  "made": "완공시기: 2010년 1월",
  "size": "대지면적: 1,394.3m² / 421.78py\n건축면적: 802.68m² / 242.81py\n연면적: 18,285.45m² / 5,531.35py\n건폐율: 57.57%\n용적률: 931.08%\n높이: 59.9m\n층수: B5 - 17F",
  "type": "Design",
  "place": "12, Dosan-daero 89-gil, Gangnam-gu, Seoul, Korea: 도산대로 89길 12, 강남구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n설계개발(DD): H-Lab + 황보 Architects + Abo Architecture Group + 나라 Architects\n구조설계: 일진 유니스코\n외장시공: Dupont Korea",
  "tags": "용도: 메디컬몰, 오피스",
  "img": []
 },
 {
  "id": "ar-l",
  "cat": "Architectural",
  "t": "Paper Dome",
  "ko": "페이퍼 돔",
  "y": "2007",
  "made": "완공시기: 2013년 1월",
  "size": "대지면적: 2,773m² / 838.83py\n건축면적: 497.92m² / 150.62py\n연면적: 2,983.21m² / 902.42py\n레지던스\n건축면적: 269.74m² / 81.60py\n연면적: 1,483.71m² / 448.82py\n건폐율: 19.87%\n용적률: 58.05%\n높이: 11.91m\n층수: B1 - 3F\n갤러리\n건축면적: 228.18m² / 69.02py\n연면적: 1,499.5m² / 453.60py\n건폐율: 16.52%\n용적률: 47.22%\n높이: 11.95m\n층수: B2 - 3F",
  "type": "Design and Construction",
  "place": "122, Saemmal-ro, Suji-gu, Yongin-si, Korea: 샘말로 122, 수지구, 용인시, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n컨셉디자인: 한원석 + H-Lab\n기본설계(SD): 한원석 + H-Lab\n설계개발(DD): H-Lab + Space E\\&C\n인테리어 디자인: H-Lab\n시공: Ryu Construction.Co.",
  "tags": "용도: 갤러리 +레지던스(주거)",
  "img": []
 },
 {
  "id": "ar-m",
  "cat": "Architectural",
  "t": "ThimBloom I & II",
  "ko": "팀블룸 I & II",
  "y": "2007",
  "made": "완공시기: 2007년 7월",
  "size": "스튜디오 면적: 94.05m² / 28.5py\n쇼룸 면적: 127.1m² / 38.45py",
  "type": "Design and Construction",
  "place": "Sinsa-dong, Gangnam-gu, Seoul, Korea: 신사동, 강남구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석\n컨셉디자인: 한원석 + H-Lab\n기본설계: 한원석 + H-Lab\n목공: 조선훈",
  "tags": "용도: 스튜디오 + 쇼룸",
  "img": []
 },
 {
  "id": "ar-n",
  "cat": "Architectural",
  "t": "Seongbuk-dong H’s House Renewal",
  "ko": "성북동 H씨 주택 리뉴얼",
  "y": "2007",
  "made": "완공시기: 2007년",
  "size": "대지면적 : 428.25m² / 129.54563py\n건축면적: 136.66m² / 41.33965py\n연면적: 410.53m² / 124.18533py\n건폐율: 31.90%\n용적률: 95.72%",
  "type": "Design and Construction",
  "place": "Seongbuk-dong, Seongbuk-gu, Seoul, Korea: 성북동, 성북구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "없음",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-o",
  "cat": "Architectural",
  "t": "SOMA: Seoul Olympic Museum of Art Renewal",
  "ko": "소마: 서울 올림픽 미술관 리뉴얼",
  "y": "2006",
  "made": "완공시기: 2006년 4월",
  "size": "대지면적: 647,416.50m²\n건축면적: 62,645.78m²\n연면적: 138,613.06m²\n건폐율: 9.68%\n용적률: 17.32%\n층수: B2-F2",
  "type": "Design and Construction",
  "place": "424, Olympic-ro, Oryun-dong, Songpa-gu, Seoul, Korea: 올림픽로 424, 오륜동, 송파구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "원(原)건축가: 조성룡\n재(再)건축가: 한원석\n리뉴얼팀: H-Lab",
  "tags": "Architectural",
  "img": []
 },
 {
  "id": "ar-p",
  "cat": "Architectural",
  "t": "Dangnim Art Museum",
  "ko": "당림미술관",
  "y": "1999",
  "made": "완공시기: 1999년 6월",
  "size": "Unknown",
  "type": "Design and Construction",
  "place": "Asan-si, Chungcheongnam-do, Korea: 아산시, 충청남도, 대한민국",
  "event": "Unknown",
  "credit": "원건축가: 한원석\n컨셉디자인: 한원석",
  "tags": "용도: 갤러리",
  "img": []
 },
 {
  "id": "ar-q",
  "cat": "Architectural",
  "t": "WooHyuk’ s Villa",
  "ko": "우혁의 빌라",
  "y": "1997",
  "made": "완공시기: 1998년 2월",
  "size": "대지면적: 128.7㎡/ 38.93py\n건축면적: 68.71㎡/ 20.78py\n연면적: 247.15㎡/ 74.76py\n건폐율: 53.39%\n용적률: 140.13%\n층수: B1 - 3F",
  "type": "Design and Construction",
  "place": "56-22, Cheongdam-dong, Gangnam-gu, Seoul, Korea: 청담동 56-22, 강남구, 서울, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 차운기\n예술작업: 한원석",
  "tags": "용도: 주거",
  "img": []
 },
 {
  "id": "ar-r",
  "cat": "Architectural",
  "t": "Bar DDong",
  "ko": "똥바",
  "y": "1995",
  "made": "완공시기: 1995년",
  "size": "Unknown",
  "type": "Installation art",
  "place": "Juan-dong, Nam-gu, Incheon, Korea: 주안동, 남구, 인천, 대한민국",
  "event": "Unknown",
  "credit": "건축가: 한원석",
  "tags": "용도: 카페, 바",
  "img": []
 },
 {
  "id": "ar-s",
  "cat": "Architectural",
  "t": "Jazz Story",
  "ko": "째즈스토리",
  "y": "1994",
  "made": "완공시기: 1994년",
  "size": "Unknown",
  "type": "Installation art",
  "place": "26-2, Samcheong-dong, Jongno-gu, Seoul, Korea: 삼청동 26-2, 종로구, 서울, 대한민국",
  "event": "Unknown",
  "img": []
 },
 {
  "cat": "Architectural",
  "t": "Tree Day",
  "y": "1994"
 }
];
